name: CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*.*.*' # Matches tags like v1.0.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies (pyproject.toml)
      run: |
        python -m pip install --upgrade pip
        pip install build
        python pypltagent-eth.py -h

    - name: Run flake8 linter
      run: |
        pip install flake8
        flake8 .

  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Build .deb package
      run: make

    - name: Upload .deb file to GitHub Release
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: pypltagent.noarch.deb
        asset_name: pypltagent-1.0.0.noarch.deb
        asset_content_type: application/vnd.debian.binary-package
